USE MASTER
GO
IF EXISTS(SELECT *
FROM SYS.DATABASES
WHERE NAME = 'PETCARX')
BEGIN
    ALTER DATABASE PETCARX SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE PETCARX
END
GO
CREATE DATABASE PETCARX
GO
USE PETCARX
GO

--1
CREATE TABLE CHINHANH
(
    MACN INT PRIMARY KEY CHECK(MACN > 0),
    TEN NVARCHAR(50),
    DIACHI NVARCHAR(100),
    SDT CHAR(10) CHECK(SDT NOT LIKE '%[^0-9]%') UNIQUE,
    THOIGIANMOCUA TIME DEFAULT('08:00:00'),
    THOIGIANDONGCUA TIME DEFAULT('22:00:00')
)
--2
CREATE TABLE NHANSU
(
    MANV INT PRIMARY KEY CHECK(MANV > 0),
    HOTEN NVARCHAR(50),
    NGAYSINH DATE,
    GIOITINH NVARCHAR(3) CHECK(GIOITINH IN (N'Nam',N'Nữ')),
    NGAYVAOLAM DATE,
    MUCLUONGCOBAN INT,
    CHUCVU NVARCHAR(20) CHECK(CHUCVU IN (N'Bác sĩ thú y', N'Nhân viên bán hàng', N'Nhân viên tiếp tân', N'Quản lý chi nhánh')),
    MACN INT FOREIGN KEY REFERENCES CHINHANH(MACN)
)
--3
CREATE TABLE LICHSUCONGTAC
(
    MANV INT CHECK(MANV > 0),
    MACN INT CHECK(MACN > 0),
    NGAYBATDAU DATE CHECK(NGAYBATDAU <= GETDATE()),
    NGAYKETTHUC DATE

        PRIMARY KEY(MANV, MACN, NGAYBATDAU)
        FOREIGN KEY(MANV) REFERENCES NHANSU(MANV),
        FOREIGN KEY(MACN) REFERENCES CHINHANH(MACN)
)
--4
CREATE TABLE DOANHTHUCHINHANH
(
    MACN INT FOREIGN KEY REFERENCES CHINHANH(MACN),
    NGAY DATE CHECK(NGAY <= GETDATE()),
    DOANHTHU BIGINT CHECK(DOANHTHU >= 0)

        CONSTRAINT DOANHTHUCHINHANH_PK PRIMARY KEY(MACN, NGAY)
)
--5
CREATE TABLE SANPHAM
(
    MASP INT PRIMARY KEY CHECK(MASP > 0),
    TEN NVARCHAR(50),
    GIABAN INT CHECK(GIABAN > 0),
    LOAI NVARCHAR(10) CHECK(LOAI IN (N'Vắc xin', N'Thuốc', N'Thức ăn', N'Phụ kiện'))
)
--6
CREATE TABLE SANPHAM_CHINHANH
(
    MASP INT CHECK(MASP > 0) FOREIGN KEY REFERENCES SANPHAM(MASP),
    MACN INT CHECK(MACN > 0) FOREIGN KEY REFERENCES CHINHANH(MACN),
    SOLUONGTONKHO INT CHECK(SOLUONGTONKHO > 0)

        PRIMARY KEY(MASP, MACN)
)
--7
CREATE TABLE DICHVU
(
    MADV INT CHECK(MADV > 0) PRIMARY KEY,
    TENDV NVARCHAR(50),
    GIANIEMYET INT,
    LOAIDV NVARCHAR(10) CHECK(LOAIDV IN (N'Khám bệnh', N'Tiêm lẻ', N'Tiêm gói'))
)
--8
CREATE TABLE DICHVU_CHINHANH
(
    MADV INT CHECK(MADV > 0) FOREIGN KEY REFERENCES DICHVU(MADV),
    MACN INT CHECK(MACN > 0) FOREIGN KEY REFERENCES CHINHANH(MACN)

        PRIMARY KEY(MADV, MACN)
)
--9
CREATE TABLE CAPBACTHANHVIEN
(
    MACAPBAC INT CHECK(MACAPBAC > 0) PRIMARY KEY,
    TENCAPBAC NVARCHAR(10) CHECK(TENCAPBAC IN (N'Cơ bản', N'Thân thiết', N'VIP')),
    CHITIEUDAT INT CHECK(CHITIEUDAT >= 0),
    CHITIEUGIU INT CHECK(CHITIEUGIU >= 0),
    PHANTRAMGIAM DECIMAL(5,4) CHECK(PHANTRAMGIAM >= 0 AND PHANTRAMGIAM < 1)
)
--10
CREATE TABLE TAIKHOANHOIVIEN
(
    MATK INT CHECK(MATK > 0),
    HOTEN NVARCHAR(50),
    SDT CHAR(10) CHECK(SDT NOT LIKE '%[^0-9]%') UNIQUE,
    EMAIL NVARCHAR(50) CHECK(EMAIL LIKE '%_@_%._%'),
    CCCD CHAR(12) CHECK(CCCD NOT LIKE '%[^0-9]%'),
    GIOITINH NVARCHAR(3) CHECK (GIOITINH IN (N'Nam', N'Nữ')),
    NGAYSINH DATE CHECK(NGAYSINH <= GETDATE()),
    DIEM_LOYALTY INT CHECK(DIEM_LOYALTY >= 0),
    SOTIENDATIEU INT CHECK(SOTIENDATIEU >= 0),
    MACAPBAC INT

        CONSTRAINT PK_TAIKHOANHOIVIEN PRIMARY KEY NONCLUSTERED(MATK),
    CONSTRAINT FK_TAIKHOANHOIVIEN_MACAPBAC FOREIGN KEY(MACAPBAC) REFERENCES CAPBACTHANHVIEN(MACAPBAC)
)
--11
CREATE TABLE DANHGIA
(
    MADG INT CHECK(MADG > 0),
    MATK INT FOREIGN KEY REFERENCES TAIKHOANHOIVIEN(MATK),
    DIEMDG DECIMAL(4,2) CHECK(DIEMDG >= 0 AND DIEMDG <= 10),
    THAIDONV DECIMAL(4,2) CHECK(THAIDONV >= 0 AND THAIDONV <= 10),
    MUCDOHAILONG DECIMAL(4,2) CHECK(MUCDOHAILONG >= 0 AND MUCDOHAILONG <= 10),
    BINHLUAN NVARCHAR(MAX)

        CONSTRAINT PK_DANHGIA PRIMARY KEY (MADG)
)
--12
CREATE TABLE THUCUNG
(
    MATC INT CHECK(MATC > 0) PRIMARY KEY,
    MATK INT,
    TEN NVARCHAR(50),
    LOAI NVARCHAR(20),
    GIONG NVARCHAR(20),
    NGAYSINH DATE,
    GIOITINH NVARCHAR(3) CHECK(GIOITINH IN (N'Nam', N'Nữ')),
    TINHTRANGSUCKHOE NVARCHAR(5) CHECK(TINHTRANGSUCKHOE IN (N'Khỏe', N'Bệnh'))

        CONSTRAINT FK_THUCUNG_MATK FOREIGN KEY(MATK) REFERENCES TAIKHOANHOIVIEN(MATK)
)
--13
CREATE TABLE KHUYENMAI
(
    MAKM INT CHECK(MAKM > 0) PRIMARY KEY,
    SOTIENGIAM INT CHECK(SOTIENGIAM > 0),
    NGAYBATDAU DATE CHECK(NGAYBATDAU <= GETDATE()),
    NGAYKETTHUC DATE
)
--14
CREATE TABLE GOITIEM
(
    MAGT INT CHECK(MAGT > 0) PRIMARY KEY,
    TENGOITIEM NVARCHAR(50),
    SOTHANG INT,
    PHANTRAMGIAM DECIMAL(5,4) CHECK(PHANTRAMGIAM > 0 AND PHANTRAMGIAM < 1)
)
--15
CREATE TABLE CHITIETGOITIEM
(
    MAGT INT FOREIGN KEY REFERENCES GOITIEM(MAGT),
    MASP INT FOREIGN KEY REFERENCES SANPHAM(MASP),
    SOLUONG INT

        PRIMARY KEY(MAGT, MASP)
)
--16
CREATE TABLE GOITIEM_CHINHANH
(
    MAGT INT FOREIGN KEY REFERENCES GOITIEM(MAGT),
    MACN INT FOREIGN KEY REFERENCES CHINHANH(MACN)

        PRIMARY KEY(MAGT, MACN)
)
--17
CREATE TABLE HOSOKHAMBENH
(
    MAKB INT CHECK(MAKB > 0) PRIMARY KEY,
    MATC INT FOREIGN KEY REFERENCES THUCUNG(MATC),
    MABACSI INT FOREIGN KEY REFERENCES NHANSU(MANV),
    NGAYHENTAIKHAM DATE
)
--18
CREATE TABLE DANGKYGOITIEM
(
    MADK INT CHECK(MADK > 0) PRIMARY KEY,
    MAGT INT FOREIGN KEY REFERENCES GOITIEM(MAGT),
    MATC INT FOREIGN KEY REFERENCES THUCUNG(MATC),
    NGAYDANGKY DATE DEFAULT GETDATE(),
    NGAYHETHAN DATE,
    SOMUIDATIEM INT CHECK(SOMUIDATIEM >= 0) DEFAULT 0
)
--19
CREATE TABLE HOSOTIEMPHONG
(
    MATP INT CHECK(MATP > 0) PRIMARY KEY,
    NGAYHEN DATE,
    MATC INT FOREIGN KEY REFERENCES THUCUNG(MATC),
    LOAIVACXIN INT FOREIGN KEY REFERENCES SANPHAM(MASP),
    NGAYTIEM DATE,
    LIEULUONG DECIMAL(6,3),
    TRANGTHAI NVARCHAR(10) CHECK (TRANGTHAI IN (N'Chưa tiêm', N'Đã tiêm')),
    MADK INT FOREIGN KEY REFERENCES DANGKYGOITIEM(MADK),
    MABACSI INT FOREIGN KEY REFERENCES NHANSU(MANV)
)
--20
CREATE TABLE HOSOTRIEUCHUNG
(
    MAKB INT FOREIGN KEY REFERENCES HOSOKHAMBENH(MAKB),
    TRIEUCHUNG NVARCHAR(50)

        PRIMARY KEY(MAKB, TRIEUCHUNG)
)
--21
CREATE TABLE HOSOCHUANDOAN
(
    MAKB INT FOREIGN KEY REFERENCES HOSOKHAMBENH(MAKB),
    CHUANDOAN NVARCHAR(50)

        PRIMARY KEY(MAKB, CHUANDOAN)
)
--22
CREATE TABLE CHITIETTOATHUOC
(
    MAKB INT FOREIGN KEY REFERENCES HOSOKHAMBENH(MAKB),
    MASP INT FOREIGN KEY REFERENCES SANPHAM(MASP),
    SOLUONG INT

        PRIMARY KEY(MAKB, MASP)
)

--23
CREATE TABLE HOADON
(
    MAHD INT CHECK(MAHD > 0),
    MATK INT,
    MAKM INT FOREIGN KEY REFERENCES KHUYENMAI(MAKM),
    NGAYLAP DATE DEFAULT(GETDATE()),
    TONGTIEN INT CHECK(TONGTIEN >= 0),
    HINHTHUCTHANHTOAN NVARCHAR(15) CHECK(HINHTHUCTHANHTOAN IN (N'Chuyển khoản', N'Tiền mặt')),
    MACN INT FOREIGN KEY REFERENCES CHINHANH(MACN),
    NVLAP INT FOREIGN KEY REFERENCES NHANSU(MANV),
    CONSTRAINT PK_HOADON PRIMARY KEY NONCLUSTERED(MAHD),
    CONSTRAINT FK_HOADON_MATK FOREIGN KEY(MATK) REFERENCES TAIKHOANHOIVIEN(MATK)
)
--24
CREATE TABLE CTHDSANPHAM
(
    MAHD INT ,
    MASP INT FOREIGN KEY REFERENCES SANPHAM(MASP),
    DONGIAHIENTAI INT CHECK(DONGIAHIENTAI > 0),
    SOLUONG INT CHECK(SOLUONG > 0),
    THANHTIEN INT CHECK(THANHTIEN > 0)

        CONSTRAINT FK_CTHDSANPHAM_MAHD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
    PRIMARY KEY(MAHD, MASP)
)
--25
CREATE TABLE CTHDDV
(
    MAHD INT,
    MATC INT FOREIGN KEY REFERENCES THUCUNG(MATC),
    MADV INT FOREIGN KEY REFERENCES DICHVU(MADV),
    DONGIAHIENTAI INT CHECK(DONGIAHIENTAI > 0),
    MADK INT FOREIGN KEY REFERENCES DANGKYGOITIEM(MADK),
    MATIEMLE INT FOREIGN KEY REFERENCES HOSOTIEMPHONG(MATP),
    MAKB INT

        CONSTRAINT FK_CTHDDV_MAHD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_CTHDDV_MAKB FOREIGN KEY(MAKB) REFERENCES HOSOKHAMBENH(MAKB),
    CONSTRAINT PK_CTHDDV PRIMARY KEY(MAHD, MATC, MADV)
)


---------------------------------------------TẠO PARTITION-------------------------------------------
-- Tạo partion dựa trên thuộc tính ngày của DOANHTHUCHINHANH
-- Khoảng X <= 2019-12-31, 2019-12-31 < X <= 2021-12-31, X > 2021-12-31 
ALTER DATABASE PETCARX
ADD FILEGROUP DOANHTHU_B2020

ALTER DATABASE PETCARX
ADD FILEGROUP DOANHTHU_A2022
GO

DECLARE @DataPath NVARCHAR(260);

SELECT @DataPath = CAST(SERVERPROPERTY('InstanceDefaultDataPath') AS NVARCHAR(260));

EXEC('
ALTER DATABASE PETCARX ADD FILE
(
    NAME = DOANHTHU_B2020,
    FILENAME = ''' + @DataPath + 'DOANHTHU_B2020.ndf'',
    SIZE = 10MB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 1024KB
) TO FILEGROUP DOANHTHU_B2020
');
GO

DECLARE @DataPath NVARCHAR(260);

SELECT @DataPath = CAST(SERVERPROPERTY('InstanceDefaultDataPath') AS NVARCHAR(260));

EXEC('
ALTER DATABASE PETCARX ADD FILE
(
	NAME = DOANHTHU_A2022,
	FILENAME = ''' + @DataPath + 'DOANHTHU_A2022.ndf'',
	SIZE = 10 MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1024 KB
) TO FILEGROUP DOANHTHU_A2022   
');

GO
CREATE PARTITION FUNCTION DOANHTHU_BY_YEAR_FUNCTION(DATE)
AS RANGE LEFT
FOR VALUES ('2019-12-31', '2021-12-31')
GO
CREATE PARTITION SCHEME DOANHTHU_BY_YEAR_SCHEME
AS PARTITION DOANHTHU_BY_YEAR_FUNCTION
TO (DOANHTHU_B2020, [PRIMARY], DOANHTHU_A2022)
GO
ALTER TABLE DOANHTHUCHINHANH
DROP CONSTRAINT DOANHTHUCHINHANH_PK
GO
ALTER TABLE DOANHTHUCHINHANH
ADD PRIMARY KEY NONCLUSTERED(MACN, NGAY ASC)
ON [PRIMARY]
GO
CREATE CLUSTERED INDEX INDEX_DOANHTHU_NAM
ON DOANHTHUCHINHANH
(
	[NGAY]
) ON DOANHTHU_BY_YEAR_SCHEME(NGAY)
GO

ALTER DATABASE PETCARX
ADD FILEGROUP CAPBAC1

ALTER DATABASE PETCARX
ADD FILEGROUP CAPBAC3
GO
ALTER DATABASE PETCARX ADD FILE
(
	NAME = CAPBAC1,
	FILENAME= 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CAPBAC1.ndf',
	SIZE = 10 MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1024 KB
) TO FILEGROUP CAPBAC1

ALTER DATABASE PETCARX ADD FILE
(
	NAME = CAPBAC3,
	FILENAME= 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CAPBAC3.ndf',
	SIZE = 10 MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1024 KB
) TO FILEGROUP CAPBAC3
GO

CREATE PARTITION FUNCTION CAPBAC_FUNCTION(INT)
AS RANGE LEFT
FOR VALUES (1,2)

CREATE PARTITION SCHEME CAPBAC_SCHEME
AS PARTITION CAPBAC_FUNCTION
TO(CAPBAC1, [PRIMARY], CAPBAC3)

CREATE CLUSTERED INDEX INDEX_CAPBAC
ON TAIKHOANHOIVIEN (MACAPBAC) ON CAPBAC_SCHEME(MACAPBAC)
GO


GO
---- Thêm Partition cho thuộc tính NGAYLAP của bảng HOADON
CREATE CLUSTERED INDEX INDEX_HOADON_NGAYLAP
ON HOADON(NGAYLAP) ON DOANHTHU_BY_YEAR_SCHEME(NGAYLAP)
GO
---------------------------------------------TẠO INDEX-------------------------------------------
---- Tạo Index tìm kiếm nhanh Khách hàng theo SĐT ---- 
CREATE NONCLUSTERED INDEX idx_KhachHang_SDT
ON TAIKHOANHOIVIEN(SDT)
GO

----Kịch bản 7 Tra cứu Lịch sử Khám bệnh & Vắc-xin----
CREATE INDEX idx_HoSoKham_MATC_NGAY
ON HOSOKHAMBENH(MATC)
GO

CREATE INDEX idx_HoSoTiem_MATC_NGAY
ON HOSOTIEMPHONG (MATC, NGAYTIEM)
GO

select * from CHITIETTOATHUOC
where MAKB = 150019