USE PETCARX
GO
-- Báo cáo doanh thu theo tháng của từng chi nhánh
ALTER DATABASE PETCARX
ADD FILEGROUP DOANHTHU_B2020

ALTER DATABASE PETCARX
ADD FILEGROUP DOANHTHU_A2022
GO
ALTER DATABASE PETCARX ADD FILE
(
	NAME = DOANHTHU_B2020,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DOANHTHU_B2020.ndf',
	SIZE = 10 MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1024 KB
) TO FILEGROUP DOANHTHU_B2020

ALTER DATABASE PETCARX ADD FILE
(
	NAME = DOANHTHU_A2022,
	FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DOANHTHU_A2022.ndf',
	SIZE = 10 MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1024 KB
) TO FILEGROUP DOANHTHU_A2022
GO
CREATE PARTITION FUNCTION DOANHTHU_BY_YEAR_FUNCTION(DATE)
AS RANGE LEFT
FOR VALUES ('01/01/2020', '01/01/2022')
GO
CREATE PARTITION SCHEME DOANHTHU_BY_YEAR_SCHEME
AS PARTITION DOANHTHU_BY_YEAR_FUNCTION
TO (DOANHTHU_B2020, [PRIMARY], DOANHTHU_A2022)
GO
ALTER TABLE DOANHTHUCHINHANH
DROP CONSTRAINT DOANHTHUCHINHANH_PK
GO
ALTER TABLE DOANHTHUCHINHANH
ADD PRIMARY KEY NONCLUSTERED(MACN, NGAY ASC)
ON [PRIMARY]
GO
CREATE CLUSTERED INDEX INDEX_DOANHTHU_NAM
ON DOANHTHUCHINHANH
(
	[NGAY]
) ON DOANHTHU_BY_YEAR_SCHEME(NGAY)
GO

SELECT P.partition_number, F.name, P.rows
FROM SYS.PARTITIONS P
	JOIN SYS.destination_data_spaces DDS ON P.partition_number = DDS.destination_id
	JOIN SYS.filegroups F ON DDS.data_space_id = F.data_space_id
WHERE OBJECT_NAME(P.object_id) = 'DOANHTHUCHINHANH'
ORDER BY P.partition_number

--SELECT F.name AS FILEGROUPNAME, M.name AS LOGICALFILENAME, M.physical_name AS FILEPATH, M.size/128 AS MB
--FROM SYS.filegroups F
--JOIN SYS.master_files M ON F.data_space_id = M.data_space_id
--WHERE M.database_id = DB_ID('PETCARX')

--SELECT COUNT(*)
--FROM DOANHTHUCHINHANH
--WHERE NGAY > '01/01/2022'

-- DROP TABLE DOANHTHUCHINHANH
-- GO
-- DROP PARTITION SCHEME DOANHTHU_BY_YEAR_SCHEME
-- DROP PARTITION FUNCTION DOANHTHU_BY_YEAR_FUNCTION
-- GO
-- ALTER DATABASE PETCARX REMOVE FILE DOANHTHU_B2020
-- ALTER DATABASE PETCARX REMOVE FILE DOANHTHU_A2022

-- ALTER DATABASE PETCARX REMOVE FILEGROUP DOANHTHU_B2020
-- ALTER DATABASE PETCARX REMOVE FILEGROUP DOANHTHU_A2022
