USE PETCARX
GO

--CREATE INDEX HOSOTIEMPHONG_MATC ON HOSOTIEMPHONG(MATC)
--DROP INDEX HOSOTIEMPHONG_MATC ON HOSOTIEMPHONG

-- Tra cứu lịch sử tiêm chủng của một thú cưng cụ thể
SET STATISTICS IO ON

SELECT *
FROM HOSOTIEMPHONG TP
JOIN THUCUNG TC ON TP.MATC = TC.MATC
JOIN SANPHAM SP ON TP.LOAIVACXIN = SP.MASP
WHERE TC.MATC = 8282


SET STATISTICS IO OFF