USE PETCARX
GO

-- Tra cứu lịch sử tiêm chủng của một thú cưng cụ thể
SET STATISTICS IO ON

SELECT *
FROM HOSOTIEMPHONG_NO_INDEX TP
JOIN THUCUNG TC ON TP.MATC = TC.MATC
JOIN SANPHAM SP ON TP.LOAIVACXIN = SP.MASP
WHERE TC.MATC = 8282

SET STATISTICS IO OFF